### ISSUE TITLE
Add sync support for the "Browse and Access" Supernote feature from Chauvet 2.9.24 Release

### ISSUE THREAD

**Issue by nelinory** [nelinory/SupernoteDesktopClient#21]
Extend SDC sync to support "Browse & Access" feature

**Comment by LazyTarget** [comment]
Are you working on this currently?

**Comment by nelinory** [comment]
Hello @LazyTarget , I am working on this feature for milestone v0.8. Prof of concept is complete, currently integrating it in SDC.

**Comment by nelinory** [comment]
Implemented in release v0.8
