### ISSUE TITLE
Device is not recognized

### ISSUE THREAD

**Issue by mariovor** [nelinory/SupernoteDesktopClient#32]
I have installed v0.9.8953 and I see only "Offlince Mode" and "Disconnected" although my new Nomand A6x2 is connected and I can browse data on it via USB connection.

I am on Win 10 Enterprise, build 10.0.19045.

Logs:
```
10/29/2024 18:29:02.174 [INF] Caller: OnStartup - Sdc v0.9.8953 started...
10/29/2024 18:29:02.241 [INF] Caller: RefreshMediaDeviceInfo - Device: N/A, DriveInfo: N/A
10/29/2024 18:29:02.658 [INF] Caller: OnNavigatedTo - SupernoteDesktopClient.ViewModels.DashboardViewModel
10/29/2024 18:29:02.659 [INF] Caller: RefreshMediaDeviceInfo - Device: N/A, DriveInfo: N/A
10/29/2024 18:33:46.021 [INF] Caller: MapEventArgs - Usb Device: USB\VID_1050&PID_0407\5&6F29131&0&5, IsConnected: True
10/29/2024 18:33:47.060 [INF] Caller: RefreshMediaDeviceInfo - Device: N/A, DriveInfo: N/A
10/29/2024 18:33:47.135 [INF] Caller: RefreshMediaDeviceInfo - Device: N/A, DriveInfo: N/A
10/29/2024 18:33:47.139 [INF] Caller: RefreshMediaDeviceInfo - Device: N/A, DriveInfo: N/A
10/29/2024 18:33:47.800 [INF] Caller: OnNavigatedTo - SupernoteDesktopClient.ViewModels.SyncViewModel
10/29/2024 18:33:47.800 [INF] Caller: RefreshMediaDeviceInfo - Device: N/A, DriveInfo: N/A
10/29/2024 18:34:12.111 [INF] Caller: MapEventArgs - Usb Device: USB\VID_1050&PID_0407\5&6F29131&0&5, IsConnected: False
10/29/2024 18:34:13.113 [INF] Caller: RefreshMediaDeviceInfo - Device: N/A, DriveInfo: N/A
10/29/2024 18:34:13.114 [INF] Caller: RefreshMediaDeviceInfo - Device: N/A, DriveInfo: N/A
10/29/2024 18:35:00.928 [INF] Caller: OnNavigatedTo - SupernoteDesktopClient.ViewModels.AboutViewModel
10/29/2024 18:35:22.558 [INF] Caller: OnNavigatedTo - SupernoteDesktopClient.ViewModels.DashboardViewModel
10/29/2024 18:35:22.558 [INF] Caller: RefreshMediaDeviceInfo - Device: N/A, DriveInfo: N/A
```

Let me know if I missed some docs here...

**Comment by nelinory** [comment]
Hello @mariovor, I have improved the Supernote device detection to use usb device description instead of usb deviceID. Greatly appreciate your help in adding support for A5X2/A6X2 (Nomad) versions. Could you try the new beta build: [v0.9.9079](https://github.com/nelinory/SupernoteDesktopClient/releases/tag/v0.9.9079) and let me know how it goes.

**Comment by mariovor** [comment]
Hi @nelinory , it worked!

**Comment by nelinory** [comment]
Hello @mariovor - this is great news. Can you attach a diagnostic log - I am curious what is the usb deviceiD and the device name ? Did you try to read the Nomad nodes from the local backup by using the explore functionality ?

**Comment by mariovor** [comment]
`11/12/2024 17:59:42.256 [INF] Caller: OnStartup - Sdc v0.9.9079 started...
11/12/2024 17:59:42.620 [INF] Caller: RefreshMediaDeviceInfo - Usb Device: \\?\usb#vid_2207&pid_0007#sn078c10022857#{6ac27878-a6fa-4155-ba85-f98f491d4f33}, Description: Supernote Nomad, Model: Supernote Nomad, DriveInfo: 24,3 GB
11/12/2024 17:59:43.485 [INF] Caller: OnNavigatedTo - SupernoteDesktopClient.ViewModels.DashboardViewModel
11/12/2024 17:59:43.488 [INF] Caller: RefreshMediaDeviceInfo - Usb Device: \\?\usb#vid_2207&pid_0007#sn078c10022857#{6ac27878-a6fa-4155-ba85-f98f491d4f33}, Description: Supernote Nomad, Model: Supernote Nomad, DriveInfo: 24,3 GB
11/12/2024 17:59:48.276 [INF] Caller: OnNavigatedTo - SupernoteDesktopClient.ViewModels.SyncViewModel
11/12/2024 17:59:48.332 [INF] Caller: RefreshMediaDeviceInfo - Usb Device: \\?\usb#vid_2207&pid_0007#sn078c10022857#{6ac27878-a6fa-4155-ba85-f98f491d4f33}, Description: Supernote Nomad, Model: Supernote Nomad, DriveInfo: 24,3 GB
11/12/2024 17:59:59.482 [INF] Caller: RefreshMediaDeviceInfo - Usb Device: \\?\usb#vid_2207&pid_0007#sn078c10022857#{6ac27878-a6fa-4155-ba85-f98f491d4f33}, Description: Supernote Nomad, Model: Supernote Nomad, DriveInfo: 24,3 GB
11/12/2024 18:00:10.180 [INF] Caller: OnNavigatedTo - SupernoteDesktopClient.ViewModels.ExplorerViewModel
11/12/2024 18:01:58.775 [INF] Caller: MapEventArgs - Usb Device: USB\VID_1050&PID_0407\5&6F29131&0&1, IsConnected: True
11/12/2024 18:01:59.783 [INF] Caller: RefreshMediaDeviceInfo - Usb Device: \\?\usb#vid_2207&pid_0007#sn078c10022857#{6ac27878-a6fa-4155-ba85-f98f491d4f33}, Description: Supernote Nomad, Model: Supernote Nomad, DriveInfo: 24,3 GB
11/12/2024 18:01:59.785 [INF] Caller: RefreshMediaDeviceInfo - Usb Device: \\?\usb#vid_2207&pid_0007#sn078c10022857#{6ac27878-a6fa-4155-ba85-f98f491d4f33}, Description: Supernote Nomad, Model: Supernote Nomad, DriveInfo: 24,3 GB
11/12/2024 18:02:04.760 [INF] Caller: MapEventArgs - Usb Device: USB\VID_1050&PID_0407\5&6F29131&0&1, IsConnected: False
11/12/2024 18:02:05.762 [INF] Caller: RefreshMediaDeviceInfo - Usb Device: \\?\usb#vid_2207&pid_0007#sn078c10022857#{6ac27878-a6fa-4155-ba85-f98f491d4f33}, Description: Supernote Nomad, Model: Supernote Nomad, DriveInfo: 24,3 GB
11/12/2024 18:02:05.763 [INF] Caller: RefreshMediaDeviceInfo - Usb Device: \\?\usb#vid_2207&pid_0007#sn078c10022857#{6ac27878-a6fa-4155-ba85-f98f491d4f33}, Description: Supernote Nomad, Model: Supernote Nomad, DriveInfo: 24,3 GB
`

And yes, I can read notes on the Desktop.
